name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # Step to log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # Step to build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag repo-sync-tool:$(date +%s)

    # Step to tag the image with Docker Hub repository
    - name: Tag the image
      run: docker tag repo-sync-tool:$(date +%s) ${{ secrets.DOCKERHUB_USERNAME }}/repo-sync-tool:latest

    # Step to push the image to Docker Hub
    - name: Push the image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/repo-sync-tool:latest
